Vagrant.configure("2") do |config|
  # Base VM OS configuration
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.define "zabbix"
  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 2
  end

  # Network settings static private IP addresses
  config.vm.hostname = "zabbix"
  config.vm.network :forwarded_port, guest: 22, host: 22020
  config.vm.network "private_network", ip: "192.168.30.9", virtualbox__intnet: "default_nbnetwork"
  config.vm.network "public_network", ip: "192.168.3.109", use_dhcp_assigned_default_route: true
#    use_dhcp_assigned_default_route: true


  # Provision ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../site.yml"
    ansible.inventory_path = "../hosts.ini"
    ansible.tags = "zabbix"
    ansible.host_key_checking = "false"
    ansible.limit = "all"
  end
end

