---
- name: Set timezone to Europe/Moscow
  ansible.builtin.timezone:
    name: Europe/Moscow

- name: Add mappings to /etc/hosts
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      192.168.30.1 webserver webserver.netbox.local
      192.168.30.2 backend1 backend1.netbox.local
      192.168.30.3 backend2 backend2.netbox.local
      192.168.30.4 pgdb1 pgdb1.netbox.local
      192.168.30.5 pgdb2 pgdb2.netbox.local
      192.168.30.6 barman barman.netbox.local
      192.168.30.7 rsyslog rsyslog.netbox.local
      192.168.30.8 gluster gluster.netbox.local
      192.168.30.9 zabbix zabbix.netbox.local
      192.168.30.10 borg.borg.netbox.local

- name: Copy ruleset for remote rsyslog
  ansible.builtin.template:
    src: 50-default.conf
    dest: /etc/rsyslog.d/

- name: Restart rsyslog service
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: Install required packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - glusterfs-server
      - traceroute

- name: Create directory for share static Netbox
  ansible.builtin.file:
    path: /opt/netbox/netbox/static
    state: directory

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Copy nginx.conf
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/sites-available/netbox

- name: Copy SSL certs
  ansible.builtin.template:
    src: netbox.crt
    dest: /etc/ssl/certs/netbox.crt

- name: Copy SSL private key
  ansible.builtin.template:
    src: netbox.key
    dest: /etc/ssl/private/netbox.key

- name: Remove nginx default
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create a symbolic link to sites-enabled
  ansible.builtin.file:
    src: /etc/nginx/sites-available/netbox
    dest: /etc/nginx/sites-enabled/netbox
    state: link

- name: Restart nginx service
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Add Zabbix repository
  ansible.builtin.apt:
    deb: https://repo.zabbix.com/zabbix/7.2/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.2+ubuntu24.04_all.deb
    update_cache: yes

- name: Install zabbix-agent2
  ansible.builtin.apt:
    name: zabbix-agent2
    state: present
    update_cache: yes

- name: Copy config for zabbix-agent2
  ansible.builtin.template:
    src: zabbix_agent2.conf
    dest: /etc/zabbix/

- name: Enable and start Zabbix-agent2 services
  ansible.builtin.systemd:
    name: zabbix-agent2
    enabled: true
    state: restarted

- name: Create directory for share static Netbox
  ansible.builtin.file:
    path: /opt/netbox/netbox/static
    state: directory

- name: Mount glusterfs volume for static Netbox
  ansible.posix.mount:
    src: gluster.netbox.local:/netbox-static
    path: /opt/netbox/netbox/static
    state: mounted
    fstype: glusterfs

- name: Stop service ufw, if running
  ansible.builtin.systemd_service:
    name: ufw.service
    state: stopped
    enabled: false
    daemon_reload: true

#- name: Disable default route
#  ansible.builtin.template:
#    src: 01-netcfg.yaml
#    dest: /etc/netplan/01-netcfg.yaml
#    owner: root
#    group: root
#    mode: 0644

#- name: Restart netplan
#  ansible.builtin.command: netplan apply

#- name: Set up forward packages across routers
#  ansible.posix.sysctl:
#    name: net.ipv4.conf.all.forwarding
#    value: '1'
#    state: present

- name: Copy ruleset for nftables
  ansible.builtin.template:
    src: nftables.conf
    dest: /etc/nftables.conf

- name: Apply nftables ruleset
  ansible.builtin.shell: nft -f /etc/nftables.conf

- name: Enable nftables service
  ansible.builtin.service:
    name: nftables
    enabled: yes
