Vagrant.configure("2") do |config|
  # Base VM OS configuration
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.define "webserver"
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 1
  end

  # Network settings static private IP addresses
  config.vm.hostname = "webserver.netbox.local"
  config.vm.network :forwarded_port, guest: 22, host: 22021
  config.vm.network "private_network", ip: "192.168.30.1", virtualbox__intnet: "default_nbnetwork"
  config.vm.network "public_network", ip: "192.168.3.101", use_dhcp_assigned_default_route: true

  # Provision ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../site.yml"
    ansible.inventory_path = "../hosts.ini"
    ansible.tags = "webserver"
    ansible.host_key_checking = "false"
    ansible.limit = "all"
  end
end

